version: '3.1'

services:
  db:
    image: mariadb:10.6
    container_name: dbStudy
    restart: unless-stopped
    ports:
      - "6033:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./studyService/db:/docker-entrypoint-initdb.d

  phpmyadmin:
    image: phpmyadmin
    container_name: pmaStudy
    restart: unless-stopped
    ports:
      - 8090:8090
    links:
      - db
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_ARBITRARY: 1
      MYSQL_ROOT_PASSWORD: root
      APACHE_PORT: 8090
    depends_on:
      - db
  
  api:
    container_name: cmarket-study-service
    build:
      context: .
      dockerfile: Dockerfile
    ports:
     - "8000:80"
    links:
     - db
    restart: unless-stopped
    depends_on:
      - db
    environment:
      DATABASE_URI: mysql+asyncmy://root:root@db/courses
    
  zookeeper:
    image: confluentinc/cp-zookeeper:7.2.1
    hostname: zookeeper
    container_name: zookeeper-cmarket
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000

  kafka:
    image: confluentinc/cp-server:7.2.1
    hostname: kafka
    container_name: kafka-cmarket
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "9997:9997"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: 'zookeeper:2181'
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,PLAINTEXT_HOST:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,PLAINTEXT_HOST://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0
      KAFKA_CONFLUENT_LICENSE_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_CONFLUENT_BALANCER_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_JMX_PORT: 9997
      KAFKA_JMX_HOSTNAME: kafka
      
  kafka-ui:
    container_name: kafka-ui-cmarket
    image: provectuslabs/kafka-ui:latest
    ports:
      - 8080:8080
    depends_on:
      - kafka
    environment:
      DYNAMIC_CONFIG_ENABLED: true
    volumes:
      - ./kui/config.yaml:/etc/kafkaui/dynamic_config.yaml